### ISSUE TITLE
A complement to CRISRPRCasFinder or its own thing?

### ISSUE THREAD

**Issue by JavierFFavieres** [Russel88/CRISPRCasTyper#32]
Does this program stand on its own, or as a complement to CRISPRCasFinder? I have observed that in your papers you use both. Can CCTyper be used alone to detect CRISPR-Cas on sequences?

**Comment by Russel88** [comment]
Hi Javier. CCtyper can indeed be used alone. The reason we have used a combination in our CRISPR-Cas on plasmids paper, is that whereas CCTyper is best for detecting and typing cas operons, CRISPRCasFinder is more sensitive for CRISPR arrays. However, we also had to manually curate the CRISPR arrays to get rid of the false positives. 

In it's current form I would say CCTyper can stand on it's own. It might miss a few partly degraded arrays distant from cas operons, but it will find most. This is because CCtyper now also BLASTs known repeat sequences against regions flanking cas operons, which will detect many of those that minced (the CRISPR detecting software that CCTyper is wrapping) are not finding.

Cheers,
Jakob
